### ISSUE TITLE
Website: User registration, login, logout

### ISSUE THREAD

**Issue by bartwr** [BlocklabNL/VEL#13]
## User Story

As a user, I want to login, so I can view my personal dashboard.

## Why

A login makes it easy to see the users data, while we still preserve privacy for this user. Read about this under 'What'.

## What

- [ ] The login functionality works as designed in https://github.com/BlocklabNL/VEL/issues/8
- [ ] It uses the API as created here: https://github.com/BlocklabNL/VEL/issues/7
- [ ] It is possible to register by filling in mail adress and password
  - [ ] Email address & password are both encrypted, so even the server managers can't see email addresses or link data to a specific user
- [ ] It is possible to login by filling in mail address and password
  - [ ] After logging in you automatically get redirected to `/explorer`
- [ ] It is possible to logout

## Bounty Details

- Expected hours: 4
- Before you start on this project, mention it in the comments
- Commit quick & often
- Only one pull request can be merged. In case multiple people worked on the task, the person that gets its PR merged has to take care of redistribution.

## How to test?

- [ ] Register
- [ ] Login
- [ ] Logout

## Acceptance Criteria

The bounty solution can be applied as soon as the following is true:

- [x] Registering works correctly
- [x] Logging in works correctly
- [x] Logging out works correctly
- [x] For these actions the API is used (you don't have to program this, it's already there)
- [x] The design is as defined in https://github.com/BlocklabNL/VEL/issues/8

**Comment by bartwr** [comment]
All checks are passed:

![image](https://user-images.githubusercontent.com/899234/48304666-88660600-e51d-11e8-9e35-18256be52713.png)

=> Issue can be closed.
